-- PostgreSQL DDL for Main.java ASM analyzer
-- Target data rule:
--   * Call/result tables store jp.co.* application classes only.
--   * jp.co.nikkobeans.framework.* is excluded from call/result data.
--   * Classes whose top-level simple name ends with Exception are excluded from call/result data.
--   * JAVA_ASM_ADAPTER_INHERIT is separate inheritance metadata and may contain an excluded
--     framework superclass so the Adapter inheritance chain remains understandable.
-- Main.java truncates all six tables with RESTART IDENTITY at startup.
-- Resolution status used in stored jp.co.* rows:
--   RESOLVED
--   NOT_FOUND_IN_GROUP
--   AMBIGUOUS_DUPLICATE_CLASS
-- METHOD_CALL may additionally contain:
--   AMBIGUOUS_METHOD_HIERARCHY
--   HIERARCHY_DEPTH_LIMIT
-- JDK / third-party resolved calls are not stored.

CREATE TABLE IF NOT EXISTS JAVA_ASM_CLASS_DEF (
    ID              BIGSERIAL PRIMARY KEY,
    GROUP_NAME      VARCHAR(512)  NOT NULL,
    JAR_PATH        TEXT          NOT NULL,
    CLASS_NAME      VARCHAR(1024) NOT NULL,
    CLASS_ACCESS    VARCHAR(256)  NOT NULL DEFAULT '',
    SUPER_CLASS     VARCHAR(1024) NOT NULL DEFAULT '',
    INTERFACES      TEXT          NOT NULL DEFAULT '',
    SOURCE_FILE     VARCHAR(1024) NOT NULL DEFAULT '',
    IS_ADAPTER      BOOLEAN       NOT NULL DEFAULT FALSE,
    CHECK (CLASS_NAME LIKE 'jp.co.%'),
    CHECK (SUPER_CLASS = '' OR SUPER_CLASS LIKE 'jp.co.%')
);

CREATE TABLE IF NOT EXISTS JAVA_ASM_METHOD_DEF (
    ID              BIGSERIAL PRIMARY KEY,
    GROUP_NAME      VARCHAR(512)  NOT NULL,
    JAR_PATH        TEXT          NOT NULL,
    CLASS_NAME      VARCHAR(1024) NOT NULL,
    METHOD_NAME     VARCHAR(1024) NOT NULL,
    DESCRIPTOR      TEXT          NOT NULL,
    READABLE_METHOD TEXT          NOT NULL DEFAULT '',
    METHOD_ACCESS   VARCHAR(256)  NOT NULL DEFAULT '',
    SOURCE_FILE     VARCHAR(1024) NOT NULL DEFAULT '',
    FIRST_LINE      INTEGER,
    LAST_LINE       INTEGER,
    CHECK (CLASS_NAME LIKE 'jp.co.%')
);

CREATE TABLE IF NOT EXISTS JAVA_ASM_CLASS_REF (
    ID                  BIGSERIAL PRIMARY KEY,
    GROUP_NAME          VARCHAR(512)  NOT NULL,
    ORIGIN_JAR          TEXT          NOT NULL,
    ORIGIN_CLASS        VARCHAR(1024) NOT NULL,
    FIRST_ORIGIN_METHOD TEXT          NOT NULL DEFAULT '',
    ORIGIN_SOURCE_FILE  VARCHAR(1024) NOT NULL DEFAULT '',
    FIRST_ORIGIN_LINE   INTEGER,
    REFERENCE_KIND      VARCHAR(128)  NOT NULL,
    TARGET_CLASS        VARCHAR(1024) NOT NULL,
    TARGET_JAR          TEXT          NOT NULL DEFAULT '',
    RESOLUTION_STATUS   VARCHAR(128)  NOT NULL DEFAULT '',
    CANDIDATES          TEXT          NOT NULL DEFAULT '',
    CHECK (ORIGIN_CLASS LIKE 'jp.co.%'),
    CHECK (TARGET_CLASS LIKE 'jp.co.%')
);

CREATE TABLE IF NOT EXISTS JAVA_ASM_METHOD_CALL (
    ID                       BIGSERIAL PRIMARY KEY,
    GROUP_NAME               VARCHAR(512)  NOT NULL,
    ORIGIN_JAR               TEXT          NOT NULL,
    ORIGIN_CLASS             VARCHAR(1024) NOT NULL,
    ORIGIN_METHOD            TEXT          NOT NULL DEFAULT '',
    ORIGIN_SOURCE_FILE       VARCHAR(1024) NOT NULL DEFAULT '',
    ORIGIN_LINE              INTEGER,
    OPCODE                   VARCHAR(128)  NOT NULL DEFAULT '',
    BYTECODE_OWNER           VARCHAR(1024) NOT NULL,
    CALLED_METHOD_NAME       VARCHAR(1024) NOT NULL,
    CALLED_DESCRIPTOR        TEXT          NOT NULL,
    BYTECODE_CALLED_METHOD   TEXT          NOT NULL DEFAULT '',
    DEFINITION_JAR           TEXT          NOT NULL DEFAULT '',
    DEFINITION_CLASS         VARCHAR(1024) NOT NULL DEFAULT '',
    DEFINITION_METHOD        TEXT          NOT NULL DEFAULT '',
    DEFINITION_SOURCE_FILE   VARCHAR(1024) NOT NULL DEFAULT '',
    DEFINITION_FIRST_LINE    INTEGER,
    DISPATCH                 VARCHAR(128)  NOT NULL DEFAULT '',
    RESOLUTION_STATUS        VARCHAR(128)  NOT NULL DEFAULT '',
    CANDIDATES               TEXT          NOT NULL DEFAULT '',
    CHECK (ORIGIN_CLASS LIKE 'jp.co.%'),
    CHECK (BYTECODE_OWNER LIKE 'jp.co.%'),
    CHECK (DEFINITION_CLASS = '' OR DEFINITION_CLASS LIKE 'jp.co.%')
);

-- Compact class-to-class graph derived only from actual bytecode method invocations.
-- One row = one origin JAR/class -> symbolic bytecode target class edge.
-- CALL_COUNT = number of bytecode invocation sites observed for the edge.
CREATE TABLE IF NOT EXISTS JAVA_ASM_CLASS_CALL (
    ID                  BIGSERIAL PRIMARY KEY,
    GROUP_NAME          VARCHAR(512)  NOT NULL,
    ORIGIN_JAR          TEXT          NOT NULL,
    ORIGIN_CLASS        VARCHAR(1024) NOT NULL,
    TARGET_CLASS        VARCHAR(1024) NOT NULL,
    TARGET_JAR          TEXT          NOT NULL DEFAULT '',
    RESOLUTION_STATUS   VARCHAR(128)  NOT NULL DEFAULT '',
    CANDIDATES          TEXT          NOT NULL DEFAULT '',
    CALL_COUNT          BIGINT        NOT NULL DEFAULT 0,
    CHECK (ORIGIN_CLASS LIKE 'jp.co.%'),
    CHECK (TARGET_CLASS LIKE 'jp.co.%'),
    CHECK (CALL_COUNT > 0)
);

-- Adapter superclass chain, deliberately separated from call/reference data.
-- INHERIT_DEPTH=1 is the direct superclass, 2+ are transitive ancestors.
CREATE TABLE IF NOT EXISTS JAVA_ASM_ADAPTER_INHERIT (
    ID                  BIGSERIAL PRIMARY KEY,
    GROUP_NAME          VARCHAR(512)  NOT NULL,
    ADAPTER_JAR         TEXT          NOT NULL,
    ADAPTER_CLASS       VARCHAR(1024) NOT NULL,
    INHERIT_DEPTH       INTEGER       NOT NULL,
    SUPER_CLASS         VARCHAR(1024) NOT NULL,
    SUPER_JAR           TEXT          NOT NULL DEFAULT '',
    RESOLUTION_STATUS   VARCHAR(128)  NOT NULL DEFAULT '',
    CANDIDATES          TEXT          NOT NULL DEFAULT '',
    CHECK (ADAPTER_CLASS LIKE 'jp.co.%'),
    CHECK (SUPER_CLASS LIKE 'jp.co.%'),
    CHECK (INHERIT_DEPTH > 0)
);

-- Recreate indexes so this DDL also corrects definitions from an older version.
DROP INDEX IF EXISTS JAVA_ASM_CLASS_DEF_IX1;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_DEF_IX2;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_DEF_IX3;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_DEF_IX4;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_DEF_IX5;

CREATE INDEX JAVA_ASM_CLASS_DEF_IX1
    ON JAVA_ASM_CLASS_DEF (GROUP_NAME, CLASS_NAME);
CREATE INDEX JAVA_ASM_CLASS_DEF_IX2
    ON JAVA_ASM_CLASS_DEF (CLASS_NAME);
CREATE INDEX JAVA_ASM_CLASS_DEF_IX3
    ON JAVA_ASM_CLASS_DEF (GROUP_NAME, JAR_PATH, CLASS_NAME);
CREATE INDEX JAVA_ASM_CLASS_DEF_IX4
    ON JAVA_ASM_CLASS_DEF (GROUP_NAME, CLASS_NAME)
    WHERE IS_ADAPTER = TRUE;


DROP INDEX IF EXISTS JAVA_ASM_METHOD_DEF_IX1;
DROP INDEX IF EXISTS JAVA_ASM_METHOD_DEF_IX2;
DROP INDEX IF EXISTS JAVA_ASM_METHOD_DEF_IX3;
DROP INDEX IF EXISTS JAVA_ASM_METHOD_DEF_IX4;

CREATE INDEX JAVA_ASM_METHOD_DEF_IX1
    ON JAVA_ASM_METHOD_DEF (GROUP_NAME, CLASS_NAME, METHOD_NAME);
CREATE INDEX JAVA_ASM_METHOD_DEF_IX2
    ON JAVA_ASM_METHOD_DEF (CLASS_NAME, METHOD_NAME);
CREATE INDEX JAVA_ASM_METHOD_DEF_IX3
    ON JAVA_ASM_METHOD_DEF (GROUP_NAME, JAR_PATH, CLASS_NAME, METHOD_NAME);


DROP INDEX IF EXISTS JAVA_ASM_CLASS_REF_IX1;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_REF_IX2;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_REF_IX3;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_REF_IX4;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_REF_IX5;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_REF_IX6;

CREATE INDEX JAVA_ASM_CLASS_REF_IX1
    ON JAVA_ASM_CLASS_REF (GROUP_NAME, ORIGIN_JAR, ORIGIN_CLASS);
CREATE INDEX JAVA_ASM_CLASS_REF_IX2
    ON JAVA_ASM_CLASS_REF (GROUP_NAME, TARGET_CLASS);
CREATE INDEX JAVA_ASM_CLASS_REF_IX3
    ON JAVA_ASM_CLASS_REF (GROUP_NAME, ORIGIN_CLASS, TARGET_CLASS);
CREATE INDEX JAVA_ASM_CLASS_REF_IX4
    ON JAVA_ASM_CLASS_REF (TARGET_CLASS);
CREATE INDEX JAVA_ASM_CLASS_REF_IX5
    ON JAVA_ASM_CLASS_REF (GROUP_NAME, REFERENCE_KIND);


DROP INDEX IF EXISTS JAVA_ASM_METHOD_CALL_IX1;
DROP INDEX IF EXISTS JAVA_ASM_METHOD_CALL_IX2;
DROP INDEX IF EXISTS JAVA_ASM_METHOD_CALL_IX3;
DROP INDEX IF EXISTS JAVA_ASM_METHOD_CALL_IX4;
DROP INDEX IF EXISTS JAVA_ASM_METHOD_CALL_IX5;
DROP INDEX IF EXISTS JAVA_ASM_METHOD_CALL_IX6;
DROP INDEX IF EXISTS JAVA_ASM_METHOD_CALL_IX7;

CREATE INDEX JAVA_ASM_METHOD_CALL_IX1
    ON JAVA_ASM_METHOD_CALL (GROUP_NAME, ORIGIN_JAR, ORIGIN_CLASS);
CREATE INDEX JAVA_ASM_METHOD_CALL_IX2
    ON JAVA_ASM_METHOD_CALL (GROUP_NAME, BYTECODE_OWNER, CALLED_METHOD_NAME);
CREATE INDEX JAVA_ASM_METHOD_CALL_IX3
    ON JAVA_ASM_METHOD_CALL (GROUP_NAME, ORIGIN_CLASS, BYTECODE_OWNER);
CREATE INDEX JAVA_ASM_METHOD_CALL_IX4
    ON JAVA_ASM_METHOD_CALL (GROUP_NAME, CALLED_METHOD_NAME);
CREATE INDEX JAVA_ASM_METHOD_CALL_IX5
    ON JAVA_ASM_METHOD_CALL (GROUP_NAME, DEFINITION_JAR, DEFINITION_CLASS);
CREATE INDEX JAVA_ASM_METHOD_CALL_IX6
    ON JAVA_ASM_METHOD_CALL (GROUP_NAME, RESOLUTION_STATUS)
    WHERE RESOLUTION_STATUS <> 'RESOLVED';


DROP INDEX IF EXISTS JAVA_ASM_CLASS_CALL_IX1;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_CALL_IX2;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_CALL_IX3;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_CALL_IX4;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_CALL_IX5;
DROP INDEX IF EXISTS JAVA_ASM_CLASS_CALL_IX6;

CREATE UNIQUE INDEX JAVA_ASM_CLASS_CALL_IX1
    ON JAVA_ASM_CLASS_CALL (GROUP_NAME, ORIGIN_JAR, ORIGIN_CLASS, TARGET_CLASS);
CREATE INDEX JAVA_ASM_CLASS_CALL_IX2
    ON JAVA_ASM_CLASS_CALL (GROUP_NAME, ORIGIN_CLASS);
CREATE INDEX JAVA_ASM_CLASS_CALL_IX3
    ON JAVA_ASM_CLASS_CALL (GROUP_NAME, TARGET_CLASS);
CREATE INDEX JAVA_ASM_CLASS_CALL_IX4
    ON JAVA_ASM_CLASS_CALL (GROUP_NAME, TARGET_JAR, TARGET_CLASS);
CREATE INDEX JAVA_ASM_CLASS_CALL_IX5
    ON JAVA_ASM_CLASS_CALL (ORIGIN_CLASS, TARGET_CLASS);


DROP INDEX IF EXISTS JAVA_ASM_ADAPTER_INHERIT_IX1;
DROP INDEX IF EXISTS JAVA_ASM_ADAPTER_INHERIT_IX2;
DROP INDEX IF EXISTS JAVA_ASM_ADAPTER_INHERIT_IX3;
DROP INDEX IF EXISTS JAVA_ASM_ADAPTER_INHERIT_IX4;

CREATE UNIQUE INDEX JAVA_ASM_ADAPTER_INHERIT_IX1
    ON JAVA_ASM_ADAPTER_INHERIT (GROUP_NAME, ADAPTER_JAR, ADAPTER_CLASS, INHERIT_DEPTH);
CREATE INDEX JAVA_ASM_ADAPTER_INHERIT_IX2
    ON JAVA_ASM_ADAPTER_INHERIT (GROUP_NAME, ADAPTER_CLASS, INHERIT_DEPTH);
CREATE INDEX JAVA_ASM_ADAPTER_INHERIT_IX3
    ON JAVA_ASM_ADAPTER_INHERIT (GROUP_NAME, SUPER_CLASS);
CREATE INDEX JAVA_ASM_ADAPTER_INHERIT_IX4
    ON JAVA_ASM_ADAPTER_INHERIT (SUPER_CLASS);

-- Planner statistics matter immediately after the bulk load.
-- Main.java executes ANALYZE for these six tables after all groups are loaded.
